repository-paths:
  ########## GitLab repositories ##########
  java8RepoUrlGitlab: 'https://git.epam.com/epmd-edp/temp/repos-for-autotests/java8-maven.git'
  java8GradleRepoUrlGitlab: 'https://git.epam.com/epmd-edp/temp/repos-for-autotests/java8-gradle.git'
  java11RepoUrlGitlab: 'https://git.epam.com/epmd-edp/temp/repos-for-autotests/java11-gradle.git'
  java11MavenRepoUrlGitlab: 'https://git.epam.com/epmd-edp/temp/repos-for-autotests/java11-maven.git'
  dotnet31RepoUrlGitlab: 'https://git.epam.com/epmd-edp/temp/repos-for-autotests/dotnet-3-1.git'
  dotnet21RepoUrlGitlab: 'https://git.epam.com/epmd-edp/temp/repos-for-autotests/dotnet-2-1.git'
  python38RepoUrlGitlab: 'https://git.epam.com/epmd-edp/temp/repos-for-autotests/python-3-8.git'
  javascriptRepoUrlGitlab: 'https://git.epam.com/epmd-edp/temp/repos-for-autotests/javascript-react.git'
  goBeegoRepoUrlGitlab: 'https://git.epam.com/epmd-edp/temp/repos-for-autotests/go-beego.git'
  goOperatorSdkUrlGitlab: 'https://git.epam.com/epmd-edp/temp/repos-for-autotests/go-operator-sdk.git'
  java8MultimoduleGitlab: 'https://git.epam.com/epmd-edp/temp/repos-for-autotests/java8-maven-multimodule.git'
  java11MultimoduleGitlab: 'https://git.epam.com/epmd-edp/temp/repos-for-autotests/java11-maven-multimodule.git'
  terraformRepoUrlGitlab: 'https://git.epam.com/epmd-edp/temp/repos-for-autotests/terraform.git'
  ######### GitHub repositories ##########
  java8MavenRepoUrlGithub: 'https://github.com/dfkononov/java-maven-java8.git'
  java8GradleRepoUrlGithub: 'https://github.com/dfkononov/java-gradle-java8.git'
  java11MavenRepoUrlGithub: 'https://github.com/dfkononov/java-maven-java11.git'
  java11GradleRepoUrlGithub: 'https://github.com/dfkononov/java-gradle-java11.git'
  java8MultimoduleGithub: 'https://github.com/dfkononov/java-maven-java8-multimodule.git'
  java11MultimoduleGithub: 'https://github.com/dfkononov/java-maven-java11-multimodule.git'
  goBeegoRepoUrlGithub: 'https://github.com/dfkononov/go-go-beego.git'
  goOperatorSdkUrlGithub: 'https://github.com/dfkononov/go-go-operator-sdk.git'
  javascriptRepoUrlGithub: 'https://github.com/dfkononov/javascript-npm-react.git'
  python38RepoUrlGithub: 'https://github.com/dfkononov/python-python-python-3.8.git'
  dotnet31RepoUrlGithub: 'https://github.com/dfkononov/dotnet-dotnet-dotnet-3.1.git'
  dotnet21RepoUrlGithub: 'https://github.com/dfkononov/dotnet-dotnet-dotnet-2.1.git'
  terraformRepoUrlGithub: 'https://github.com/dfkononov/terraform-terraform.git'
  #########
  petclinicBeRepoUrlGitlab: 'https://git.epam.com/epmd-edp/examples/3tier/3-tier-app-be.git'
  petclinicFeRepoUrlGitlab: 'https://git.epam.com/epmd-edp/examples/3tier/3-tier-app-fe.git'
  petclinicAutotestsUrlGitlab: 'https://git.epam.com/epmd-edp/examples/3tier/3-tier-app-tests.git'
  petclinicDeployUrl: 'https://github.com/SergK/spring-petclinic.git'